name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}Bukkit
version: ${project.version}
api-version: 1.13
author: MiaoWoo
website: ${ciManagement.url}
load: STARTUP
